### ISSUE TITLE
Source link for renamed module disappears

### ISSUE THREAD

**Issue by hunse** [nengo/nengo-sphinx-theme#55]
With `nengo_sphinx_theme.ext.renamed_autoautosummary`, the `[source]` links for `nengo_sphinx_theme.ext.renamed_autoautosummary.a_test_function` and `nengo_sphinx_theme.ext.renamed_autoautosummary.TestClass` do not appear.

This is related to the following error that appears in the docs build output for this repo:
```
Traceback (most recent call last):
  File "/home/eric/venv/full3/lib/python3.6/site-packages/sphinx/ext/viewcode.py", line 35, in _get_full_modname
    return get_full_modname(modname, attribute)
  File "/home/eric/venv/full3/lib/python3.6/site-packages/sphinx/util/__init__.py", line 331, in get_full_modname
    module = import_module(modname)
  File "/home/eric/venv/full3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nengo_sphinx_theme.ext.renamed_autoautosummary'
viewcode can't import nengo_sphinx_theme.ext.renamed_autoautosummary, failed with error "No module named 'nengo_sphinx_theme.ext.renamed_autoautosummary'"
```

This does not appear to be a problem e.g. in the Nengo docs, when we rename classes like `nengo.neurons.LIF` to `nengo.LIF`. The difference could be that there we're renaming a single class, whereas here we're renaming a module.

**Comment by tbekolay** [comment]
We looked into this a bit, and indeed the issue is renaming modules. The ability to rename modules still makes sense, but in this case it fails because you can't actually import the renamed module.

The resolution to this issue therefore doesn't seem like we should make it possible, but we should raise an explicit error here because it's not something we want people to do accidentally. Then we should change the example we render in the docs.

However, since the resolution doesn't change behaviour, we're probably not going to put in any cycles to this any time soon.
